name: Encypt_Decrypt
run-name: ${{ github.actor }} is executing Pipeline
on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Select Environment'
        required: true
        default: 'Select'
        type: choice
        options:
        - Development
        - Test
        - Stage
        - Production
      Operation:    
        description: 'Select Operation'
        required: true
        default: 'Select'
        type: choice
        options:
        - Encrypt
        - Decrypt
      Property:
        description: 'Provide the property'
        required: true
        type: string
      Property_Type:
        description: 'Provide the property type'
        required: true
        default: 'Select'
        type: choice
        options:
        - YAML
        - PROPERTY
        - PAYLOAD
        
jobs:           
  Encrypt_Decrypt:
    runs-on: windows-2019
    environment: ${{ inputs.Environment }}
    steps:
      - name: Cloning Input File
        uses: actions/checkout@v3
      - name: Gettin Credentials
        shell: pwsh
      - name: Performing Encypt/Decrypt Operation
        shell: pwsh
        env:
          Environment: ${{ inputs.Environment }}
          Property: ${{ inputs.Environment }}
        run: |
          function response{
            write-Host "Property:: $inputs.Property"
          }
          $gettingresponse=response
      
